name: Render Deploy

# このワークフローがトリガーされるタイミングを指定
on:
  push: #git push時に自動実行
    branches:
      - main
  # GitHubのUIから手動で実行できるようにする
  #workflow_dispatch:

jobs:
  # デプロイを行うジョブ
  deploy:
    runs-on: ubuntu-latest
    # 環境変数にAPIキーをセット
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          # Render.comのデプロイ用APIを呼び出す
          curl -X POST "https://api.render.com/deploy/srv-cppbvt2j1k6c73801m9g?key=$RENDER_API_KEY"